config/routes.rb
Rails.application.routes.draw do

  get '/cocktail-search', to: 'cis#search'
  post '/cocktail-search', to: 'cis#filter'
  get '/search-results', to: 'cis#index', as: 'results'
  resources :ucs

  root "homepage#home"
  
  get '/cocktails', to: 'cocktails#index'
  get '/cocktails/new', to: 'cocktails#new', as: 'new_cocktail'
  post '/cocktails', to: 'cocktails#create'
  get '/cocktails/:id', to: 'cocktails#show', as: 'cocktail'
  get '/cocktails/:id/edit', to: 'cocktails#edit', as: 'edit_cocktail'
  patch '/cocktails/:id', to: 'cocktails#update'
  delete '/cocktails/:id', to: 'cocktails#destroy'

  get '/ingredients', to: 'ingredients#index'
  get '/ingredients/new', to: 'ingredients#new', as: 'new_ingredient'
  post '/ingredients', to: 'ingredients#create'
  get '/ingredients/:id', to: 'ingredients#show', as: 'ingredient'
  get '/ingredients/:id/edit', to: 'ingredients#edit', as: 'edit_ingredient'
  patch '/ingredients/:id', to: 'ingredients#update'
  delete '/ingredients/:id', to: 'ingredients#destroy'

  get "/signup" => "users#new"
  post "/signup" => "users#new"
  post "/users" => "users#create"

  get "/editprofile" => "users#edit"
  patch "/users/:id" => "users#update"

  get "/delete" => "users#destroy"
  post "/" => "users#destroy"

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/logout', to: 'sessions#new'

  get "/users/:id" => 'users#show', as: "user" #need to refactor for security

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def home
    @rating = [1, 2, 3, 4, 5]
  end
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/homepage/home.html.erb
<%# <h1>Homepage#home</h1>
<p>Find me in app/views/homepage/home.html.erb</p> %>
<head>
<title>Cosmos</title>
</head>
<body class="home">
<div class="home">
<h1 class="home">Cosmos</h1>
<h2>Your premier cocktail resource from this galaxy to the next</h2>

<h2><%= form_tag(cocktails_path, method: "get", autocomplete: "off") do %>
  Search by Name <%= text_field_tag :name %>
  <input type="submit" class="button" value="Search">
<% end %>
</h2>

<h2>
<%= form_tag(ucs_path, method: "get") do %>
  Search by Rating <%= select_tag :rating, options_from_collection_for_select(@rating, "to_i", "to_i") %>
  <input type="submit" class="button" value="Search">
<% end %></h2>
</div>
</body>