config/routes.rb
Rails.application.routes.draw do

  get '/cocktail-search', to: 'cis#search'
  post '/cocktail-search', to: 'cis#filter'
  get '/search-results', to: 'cis#index', as: 'results'
  resources :ucs

  root "homepage#home"
  
  get '/cocktails', to: 'cocktails#index'
  get '/cocktails/new', to: 'cocktails#new', as: 'new_cocktail'
  post '/cocktails', to: 'cocktails#create'
  get '/cocktails/:id', to: 'cocktails#show', as: 'cocktail'
  get '/cocktails/:id/edit', to: 'cocktails#edit', as: 'edit_cocktail'
  patch '/cocktails/:id', to: 'cocktails#update'
  delete '/cocktails/:id', to: 'cocktails#destroy'

  get '/ingredients', to: 'ingredients#index'
  get '/ingredients/new', to: 'ingredients#new', as: 'new_ingredient'
  post '/ingredients', to: 'ingredients#create'
  get '/ingredients/:id', to: 'ingredients#show', as: 'ingredient'
  get '/ingredients/:id/edit', to: 'ingredients#edit', as: 'edit_ingredient'
  patch '/ingredients/:id', to: 'ingredients#update'
  delete '/ingredients/:id', to: 'ingredients#destroy'

  get "/signup" => "users#new"
  post "/signup" => "users#new"
  post "/users" => "users#create"

  get "/editprofile" => "users#edit"
  patch "/users/:id" => "users#update"

  get "/delete" => "users#destroy"
  post "/" => "users#destroy"

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/logout', to: 'sessions#new'

  get "/users/:id" => 'users#show', as: "user" #need to refactor for security

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
    belongs_to :user
    has_many :ucs
    has_many :users, through: :ucs
    has_many :cis
    has_many :ingredients, through: :cis

    validates :name, presence: true

    def ingredients_names
        self.ingredients.map { |i| i.name }
    end

    def ci_check(params)
        ing_id = params["ingredient_id"].to_i
        input_amount = params["amount"].to_i

        cis = Ci.all.select { |ci| ci.cocktail_id == self.id }

        if ci = cis.find { |ci| ci.ingredient_id == ing_id }
            if input_amount == 0
                ci.delete
            elsif input_amount != ci.amount
                ci.update(amount:input_amount)
            end
        elsif input_amount > 0
             Ci.create(cocktail_id:self.id,ingredient_id:ing_id,amount:input_amount)
        end
    end

end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :authorized, except: [:index, :show]

  def index
  @cocktails = Cocktail.all
    if params[:name]
      @cocktail = Cocktail.where('name LIKE ?', "%#{params[:name]}%")
    else
      @cocktail = Cocktail.all
    end
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @profile = User.find(@cocktail.user_id)
    @user = current_user
    @uc = Uc.new
    @rating = [1, 2, 3, 4, 5]
  end

  def new
    @cocktail = Cocktail.new
    @cis = []
    @user = current_user
  end

  def create
    @user = current_user
    @cocktail = Cocktail.new(cocktail_params)
    cis = params["cis"]
    if @cocktail.save
      cis.each do |ci|
        @cocktail.ci_check(ci)
      end
      redirect_to cocktail_path(@cocktail)
    else
      flash[:alert] = @cocktail.errors.messages
      render :new
    end
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
    @cis = Ci.all.select { |ci| ci.cocktail_id == @cocktail.id}
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    cis = params["cis"]
    if @cocktail.update(cocktail_params)
      cis.each do |ci|
        @cocktail.ci_check(ci)
      end
      redirect_to cocktail_path(@cocktail)
    else
      flash[:alert] = @cocktail.errors.messages
      render :edit
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id]).destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name,:instructions,:ice,:user_id,:search)
  end

end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/views/cocktails/_form.html.erb
<body class="form">
<%= form_for @cocktail do |f| %>
    <%= f.hidden_field :user_id, value:session[:user_id] %>
    <table class="form">
    <tr><td>Name:</td><td><%= f.text_field :name %></td></tr>
    <tr><td>Instructions:</td><td> <%= f.text_area :instructions %></td></tr>
    <tr><td>Ingredients:</td><td class="ing">
    <% Ingredient.all.each do |i| %>
        <% if @cis %>
            <% if ci = @cis.find { |ci| ci.ingredient_id == i.id } %>
                <% default_val = ci.amount %>
            <% else %>
                <% default_val = nil %>
            <% end %>
        <% else %>
            <% default_val = nil %>
        <% end %>
        <% if i.category == "Garnish"%>
            <% unit = "units" %>
        <%else %>
            <% unit = "fl oz" %>
        <%end%>
        <br><br><%= number_field_tag 'cis[][amount]', default_val%> <%=unit%>  <%=i.name%><%= hidden_field_tag 'cis[][ingredient_id]', i.id %>  
    <% end %>
    </td></tr>
    <tr colspan="2"><td><p class="submitbutton"><br><%= f.submit  %></p></td></tr>
    </table>
    
<% end %>
</body>

app/views/cocktails/edit.html.erb
<head>
<title>Edit <%= @cocktail.name %></title>
</head>
<body>

<h1>Edit <%= @cocktail.name %></h1>

<%= render 'form' %>

</body>

app/views/cocktails/index.html.erb
<head>
<title>All Cocktails</title>
</head>
<body class="cocktails">
<% if params[:name] %>
    <br>
    <ul>
    <% @cocktail.each do |cocktail| %>
        <li><%= link_to cocktail.name, cocktail_path(cocktail) %></li>
    <% end %>
    </ul>
<% else %>
    <h1>All Cocktails</h1>
    <p><%= link_to "Create New Cocktail", new_cocktail_path, class:"button"%></p>
    <br>
    <ul class="list">
    <% @cocktails.each do |cocktail| %>
        <li><%= link_to cocktail.name, cocktail_path(cocktail) %></li>
    <% end %>
    </ul>
<% end %>
</body>

app/views/cocktails/new.html.erb
<head>
<title>Create New Cocktail</title>
</head>
<body>

<h1>Create New Cocktail</h1>

<br>
<% if flash[:alert] %>
    <p class="alert"><%= flash[:alert] %></p>
<% end %>
<%= render 'form' %>

</body>

app/views/cocktails/show.html.erb
<head>
<title><%= @cocktail.name %></title>
</head>
<body>

<h1><%= @cocktail.name %></h1>
<p><em>Submitted by <%=link_to @profile.name, user_path(@profile)%></em></p>
<br>
<br>

<table class="show">
    <tr>
        <td rowspan="2" class="recipecard"><h2>Ingredients Used:</h2>
                    <ul>
            <% @cocktail.cis.each do |ci| %>
                <li><%= ci.amount %> fl oz   <%= ci.ingredient.name %></li>
            <% end %>
            </ul>
        </td>
        <td class="title"><h2>Instructions:</h2></td>
    </tr>
    <tr>
        <td><h3><%= @cocktail.instructions %></h3></td>
    </tr>
</table>
<p>
<%= @cocktail.ucs.average(:rating) %></p>
<br>
<% if !session[:user_id].nil? %>
    <% if !(@user.id == @cocktail.user_id)%>
        <%= form_for @uc do |f| %>
        <%= f.collection_select :rating, @rating, :to_i, :to_i %>
        <input type="hidden" name="uc[cocktail_id]" value="<%=@cocktail.id%>"/>
        <%= f.submit "Rate Drink!" %>
        <% end %>
    <% end %>
<% end %>

<br>
<br>
<br>
<br>
<p class="links">
<%= link_to "Edit Cocktail", edit_cocktail_path(@cocktail), class:"button" %> 
<%= link_to "Delete Cocktail", cocktail_path(@cocktail), method: "delete", class:"button" %>
<%= link_to "Back to Cocktail List", cocktails_path, class:"button" %></p>


</body>