config/routes.rb
Rails.application.routes.draw do

  get '/cocktail-search', to: 'cis#search'
  post '/cocktail-search', to: 'cis#filter'
  get '/search-results', to: 'cis#index', as: 'results'
  resources :ucs

  root "homepage#home"
  
  get '/cocktails', to: 'cocktails#index'
  get '/cocktails/new', to: 'cocktails#new', as: 'new_cocktail'
  post '/cocktails', to: 'cocktails#create'
  get '/cocktails/:id', to: 'cocktails#show', as: 'cocktail'
  get '/cocktails/:id/edit', to: 'cocktails#edit', as: 'edit_cocktail'
  patch '/cocktails/:id', to: 'cocktails#update'
  delete '/cocktails/:id', to: 'cocktails#destroy'

  get '/ingredients', to: 'ingredients#index'
  get '/ingredients/new', to: 'ingredients#new', as: 'new_ingredient'
  post '/ingredients', to: 'ingredients#create'
  get '/ingredients/:id', to: 'ingredients#show', as: 'ingredient'
  get '/ingredients/:id/edit', to: 'ingredients#edit', as: 'edit_ingredient'
  patch '/ingredients/:id', to: 'ingredients#update'
  delete '/ingredients/:id', to: 'ingredients#destroy'

  get "/signup" => "users#new"
  post "/signup" => "users#new"
  post "/users" => "users#create"

  get "/editprofile" => "users#edit"
  patch "/users/:id" => "users#update"

  get "/delete" => "users#destroy"
  post "/" => "users#destroy"

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/logout', to: 'sessions#new'

  get "/users/:id" => 'users#show', as: "user" #need to refactor for security

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :cis
    has_many :cocktails, through: :cis

    validates :name, presence: true
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :authorized, except: [:index, :show]
  
  def index
    @ingredients = Ingredient.all
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end

  def new
    @categories = ["Liquor", "Mixer", "Garnish"]
    @ingredient = Ingredient.new
  end

  def create
    @categories = ["Liquor", "Mixer", "Garnish"]
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      flash[:message] = "Ingredient Created!"
      redirect_to ingredient_path(@ingredient)
    else
      flash.now[:message] = @ingredient.errors.full_messages[0]
      render :new
    end
  end

  def edit
    @categories = ["Liquor", "Mixer", "Garnish"]
    @ingredient = Ingredient.find(params[:id])
  end

  def update
    @categories = ["Liquor", "Mixer", "Garnish"]
    @ingredient = Ingredient.find(params[:id])
    if @ingredient.update(ingredient_params)
      flash[:message] = "Ingredient Updated!"
      redirect_to ingredient_path(@ingredient)
    else
      flash.now[:message] = @ingredient.errors.full_messages[0]
      render :edit
    end
  end

  def destroy
    Ingredient.find(params[:id]).destroy
    redirect_to ingredients_path
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:name,:category)
  end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<body class="form">
<% if flash[:message]%>
    <%= flash[:message]%>
<% end %>
<table class="form">
<%= form_for @ingredient do |f| %>
    <tr>
        <td>Name:</td>
        <td><%= f.text_field :name %></td>
    </tr>
    <tr>
        <td>Type:</td>
        <div class="select">
        <td><%= f.collection_select :category, @categories, :to_s, :to_s, include_blank: false %></td>
        </div>
    </tr>
    <tr>
        <td colspan="2"><p><%= f.submit %></p></td>
    </tr>
    </table>
<% end %>

</body>

app/views/ingredients/edit.html.erb
<head>
<title>Edit <%= @ingredient.name %></title>
</head>
<body>
<h1>Edit <%=@ingredient.name %></h1>

<%= render 'form' %>

</body>

app/views/ingredients/index.html.erb
<head>
<title>All Ingredients</title>
</head>
<body class="ingredients">

<h1>All Ingredients</h1>
<% if params[:name] %>
    <br>
    <ul class="list">
    <% @cocktail.each do |cocktail| %>
        <li><%= link_to cocktail.name, cocktail_path(cocktail) %></li>
    <% end %>
    </ul>
<% else %>
    <p><%= link_to "Add New Ingredient", new_ingredient_path, method: "get", class:"button" %></p>
    <br>
    <ul class="list">
    <% @ingredients.each do |ingredient| %>
        <li><%= link_to ingredient.name, ingredient_path(ingredient)%></li></div>
    <% end %>
    </ul>
<%end%>

</body>

app/views/ingredients/new.html.erb
<head>
<title>Add Ingredient</title>
</head>
<body>
<h1>Add an Ingredient</h1>

<%= render 'form' %>

</body>

app/views/ingredients/show.html.erb
<head>
<title><%= @ingredient.name %></title>
</head>
<body>
<h1><%= @ingredient.name %></h1>

Type: <%= @ingredient.category %>
<br>
<br>
<%= link_to "Edit Ingredient", edit_ingredient_path, class:"button" %>
<%= link_to "Delete Ingredient", ingredient_path(@ingredient), method: "delete", class:"button" %>
<%= link_to "Back To Ingredient List", ingredients_path, class:"button" %>

</body>