config/routes.rb
Rails.application.routes.draw do

  get '/cocktail-search', to: 'cis#search'
  post '/cocktail-search', to: 'cis#filter'
  get '/search-results', to: 'cis#index', as: 'results'
  resources :ucs

  root "homepage#home"
  
  get '/cocktails', to: 'cocktails#index'
  get '/cocktails/new', to: 'cocktails#new', as: 'new_cocktail'
  post '/cocktails', to: 'cocktails#create'
  get '/cocktails/:id', to: 'cocktails#show', as: 'cocktail'
  get '/cocktails/:id/edit', to: 'cocktails#edit', as: 'edit_cocktail'
  patch '/cocktails/:id', to: 'cocktails#update'
  delete '/cocktails/:id', to: 'cocktails#destroy'

  get '/ingredients', to: 'ingredients#index'
  get '/ingredients/new', to: 'ingredients#new', as: 'new_ingredient'
  post '/ingredients', to: 'ingredients#create'
  get '/ingredients/:id', to: 'ingredients#show', as: 'ingredient'
  get '/ingredients/:id/edit', to: 'ingredients#edit', as: 'edit_ingredient'
  patch '/ingredients/:id', to: 'ingredients#update'
  delete '/ingredients/:id', to: 'ingredients#destroy'

  get "/signup" => "users#new"
  post "/signup" => "users#new"
  post "/users" => "users#create"

  get "/editprofile" => "users#edit"
  patch "/users/:id" => "users#update"

  get "/delete" => "users#destroy"
  post "/" => "users#destroy"

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/logout', to: 'sessions#new'

  get "/users/:id" => 'users#show', as: "user" #need to refactor for security

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ci.rb
class Ci < ApplicationRecord
    belongs_to :cocktail
    belongs_to :ingredient
end

app/controllers/cis_controller.rb
class CisController < ApplicationController
  def search
    @rating = [1, 2, 3, 4, 5]
    @liquors = Ingredient.all.select { |i| i.category == "Liquor" }
    @mixers = Ingredient.all.select { |i| i.category == "Mixer" }
    @garnishes = Ingredient.all.select { |i| i.category == "Garnish" }
    # @ingredients = (Ingredient.all.sort_by { |i| i.category }).map { |i| i.name }
  end

  def filter
    @rating = [1, 2, 3, 4, 5]
    @ingredients = params[:ingredients]
    @search_type = params[:search_type]
    redirect_to :controller => "index", :action => "get", :ingredients => @ingredients, :search_type => @search_type
  end

  def index
    @ingredients = params[:ingredients]
    not_empty_cocktails = Cocktail.all.select { |c| c.ingredients.size > 0 }
    
    case params[:search_type]
    when "include"
      @cocktails = not_empty_cocktails.find_all { |c| (@ingredients - c.ingredients_names).size < @ingredients.size }
    when "only"
      @cocktails = not_empty_cocktails.find_all { |c| (c.ingredients_names - @ingredients).empty? }
    when "exclude"
      @cocktails = not_empty_cocktails.find_all { |c| (c.ingredients_names - @ingredients).size == c.ingredients_names.size }
    end

  end
end

app/helpers/cis_helper.rb
module CisHelper
end

app/views/cis/index.html.erb
<head>
<title>Search Results</title>
</head>
<body>
<h1>Cocktails</h1>
<br>
<table>
<% @cocktails.each_with_index do |cocktail,i| %>
    <% i = i+1 %>
    <% if i % 5 == 1 %>
        <tr><td><%= link_to cocktail.name, cocktail_path(cocktail), class:"cocktail" %></a?</td>
    <% elsif i % 5 == 0 %>
        <td><%= link_to cocktail.name, cocktail_path(cocktail),class:"cocktail" %></td></tr>
    <%else%>
        <td><%= link_to cocktail.name, cocktail_path(cocktail),class:"cocktail" %></td>
    <%end%>
<% end %>
</table>

</body>

app/views/cis/search.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Cocktail Search</title>
    </head>

    <body class="search">
    <h1>Cocktail Search</h1>
    <div class="space">
<%= form_tag(results_path,method:'get') %>
    <p class="big">Show me cocktails that... </p>
        <p>
        <input type="radio" name="search_type", value="include", id="include" checked><label for="include">Include</label>

        <input type="radio" name="search_type", value="exclude", id="exclude"><label for="exclude">Exclude</label>

        <input type="radio" name="search_type", value="only", id="use only"><label for="use only">Use Only</label>
        </p>
    <p class="big">... these ingredients:</p>
    <hr>
    <ul class="blackout">
    <p class="big">LIQUORS</p>
    <% @liquors.each do |i| %>
        <li><p><input type="checkbox" name="ingredients[]" value=<%=i.name%> id=<%=i.name%> ><label for=<%=i.name%>> <%=i.name%></label></p>
    <% end %>
    <br>
    <p class="big">MIXERS</p>
    <% @mixers.each do |i| %>
        <li><p><input type="checkbox" name="ingredients[]" value=<%=i.name%> id=<%=i.name%> ><label for=<%=i.name%>> <%=i.name%></label></p>
    <% end %>
    <br>
    <p class="big">GARNISHES</p>
    <% @garnishes.each do |i| %>
        <li><p><input type="checkbox" name="ingredients[]" value=<%=i.name%> id=<%=i.name%> ><label for=<%=i.name%>> <%=i.name%></label></p>
    <% end %>
    </ul>

    <br>
    <p><input type="submit" class="button" value="Search Cocktails"></p>
    </div>
    </body>
</html>